version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat
    volumes:
      - database:/var/lib/postgresql/data
      # - ./initdb:/docker-entrypoint-initdb.d
  web:
    build: .
    command: yarn start
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  database:
