version: 2
jobs:
  build:
    docker:
      - image: node:10.14.2
      # specify the version you desire here
      - image: postgres
        name: db
        environment:
          POSTGRES_DB: chat
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres

    working_directory: /app

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: node -v
      - run: yarn --varsion
      - run: yarn install
      - run:
          name: dockerize をインストール
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: db を待機
          command: dockerize -wait tcp://db:5432 -timeout 1m
      - run: yarn test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


# version: 2.1
# orbs:
#   node: circleci/node@1.1.6
# jobs:
#   build:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - node/with-cache:
#           steps:
#             - run: npm install
#             - run: npm test
# workflows:
#     build:
#       jobs:
#         - build